### ISSUE TITLE
File size is incorrect type causing a json parser error

### ISSUE THREAD

**Issue by cviktor** [microsoft/MK.IO#12]
Invalid API schema definition

For the `Assets. ListTracksAndDirListingAsync` call the API returns the file size (probably in byte) defined as an int, but because the https://github.com/microsoft/MK.IO/blob/main/MK.IO/CsharpDotNet2/Model/FileSchema.cs defines the size as an int for a 4.5 Gb file I get an error
```
Newtonsoft.Json.JsonReaderException: JSON integer 4999445460 is too large or small for an Int32. Path 'spec.files[0].size', line 13, position 26.
```

**Comment by xpouyat** [comment]
Oh, thanks for the issue creation. I will look to it.

**Comment by xpouyat** [comment]
Hello,
SDK v1.6.3 should fix this issue.
https://www.nuget.org/packages/MK.IO/1.6.3

**Comment by xpouyat** [comment]
@cviktor Please confirm it solves your problem.
