### ISSUE TITLE
Delete live output error "Index (zero based) must be greater than or equal to zero and less than the size of the argument list."

### ISSUE THREAD

**Issue by sturlath** [microsoft/MK.IO#16]
If I try to delete an output

` await client.LiveOutputs.DeleteAsync("liveEventName", "liveOutputName");`

I get the following error

> Index (zero based) must be greater than or equal to zero and less than the size of the argument list.

But if I just use Postman and call it directly https://docs.mk.io/reference/delete_apiamsproject_nameliveeventsevent_nameliveoutputsoutput_name it works no problem.

**Comment by sturlath** [comment]
@xpouyat how fast can a nuget be released if you agree with my update? 😅

**Comment by sturlath** [comment]
For others having this issue (until a new package is pushed) you can use this Refit code to solve it

```csharp
public interface ILiveOutputsApi
{
    // This API https://docs.mk.io/reference/delete_apiamsproject_nameliveeventsevent_nameliveoutputsoutput_name
    [Delete("/api/ams/{projectName}/liveEvents/{eventName}/liveOutputs/{outputName}")]
    Task DeleteAsync(string projectName, string eventName, string outputName, [Header("x-mkio-token")] string apiKey, CancellationToken cancellationToken = default);
} 
```

Then call it

```charp
await liveOutputsApi.DeleteAsync(subscriptionName, liveEventName, liveOutputName, "your mkio token");
```

Set it up like

```charp
builder.Services.AddRefitClient<ILiveOutputsApi>()
.ConfigureHttpClient(c => c.BaseAddress = new Uri("https://api.mk.io"));
```

Install Refit
```powershell
Install-Package Refit
Install-Package Refit.HttpClientFactory 
```

**Comment by xpouyat** [comment]
> @xpouyat how fast can a nuget be released if you agree with my update? 😅

I will look to it on Monday and will push a new package the same day. Is it ok?

**Comment by xpouyat** [comment]
By the way, if you migrate from AMS to MK.IO, you can request an extra month extension using my tool https://aka.ms/amse

**Comment by Sturla76** [comment]
> I will look to it on Monday and will push a new package the same day. Is it ok?

yes 100% ok np!

> By the way, if you migrate from AMS to MK.IO, you can request an extra month extension using my tool https://aka.ms/amse

That is awesome! I started way to late this migration work 😅 Ill signup tomorrow thank you very much! 👌
