### ISSUE TITLE
JobName validation triggered by valid string

### ISSUE THREAD

**Issue by christianduic** [microsoft/MK.IO#20]
I tried to update my code to the latest nuget version and I'm getting this error when running my code:

**Job name must start and end with a letter or number and can only contain the following special characters: [-_.] (Parameter 'jobName')**

My jobs names looks like this: `$"{prefix}--{id}"`. Which I tested in the MkIo ui and it's a valid name. I guess that the Regex introduced to validate the jobName is not taking in cosideration that 2 continuos - characters are a valid combination.

**Comment by xpouyat** [comment]
Thanks for the issue report.
I changed the RegEx and add some tests to the SDK.
https://github.com/microsoft/MK.IO/commit/d0629758487a80ad53bd3335ffb775cb44462962
Do you need a new version of the SDK with the fix ASAP ?

**Comment by christianduic** [comment]
Thank you for the quick response!

No, it's not urgent. I can wait for the next realease 👍🏻

**Comment by xpouyat** [comment]
Release v1.7.1 published.
