### ISSUE TITLE
Missing ContentKeyIdentifierClaimType

### ISSUE THREAD

**Issue by gabrielheming** [microsoft/MK.IO#22]
As stated on [How to use DRM to playback MK.IO assets encrypted]( https://support.mk.io/portal/en/kb/articles/how-to-use-drm-to-playback-mk-io-assets-encrypted#Playback_Asset_with_HLS_or_DASH_with_ClearKey_and_JWT_token), MK.IO will honor the usage of the claim type **"urn:microsoft:azure:mediaservices:contentkeyidentifier"**.

However, the identifier is missing (it was present on ASM package).

**Comment by xpouyat** [comment]
Thanks. I merged your pull request

**Comment by xpouyat** [comment]
In https://github.com/microsoft/MK.IO/releases/tag/v1.7.2
