### ISSUE TITLE
Value length cannot exceed 63. (Parameter 'jobName')

### ISSUE THREAD

**Issue by gabrielheming** [microsoft/MK.IO#29]
Is there any reason to limit the jobName to 63 characters?

I am migrating an existing system, and original ASM supports longer jobs names. Also, the web portal from MK.IO does not impose any limitation.

However, the job name goes on the URL as a parameter. Thus, I would suggest to use the assetName length as reference (260).

**Comment by xpouyat** [comment]
Please see this issue https://github.com/xpouyat/MK.IO/issues/59

This may be have fixed by MediaKind. I will test again.

**Comment by xpouyat** [comment]
From my tests, length can now be up to 260 characters. Space is prohibited. I will update the code. Thanks !

**Comment by gabrielheming** [comment]
I've made a PR for that.

**Comment by xpouyat** [comment]
I changed the code in dev https://github.com/microsoft/MK.IO/commit/e688834311557a6b619584f6cecb735354ad609e Thanks !

**Comment by xpouyat** [comment]
Released in version https://github.com/microsoft/MK.IO/releases/tag/v1.7.2
