### ISSUE TITLE
LiveEventInputProtocol set to SRT doesn´t work 

### ISSUE THREAD

**Issue by sturlath** [microsoft/MK.IO#35]
When setting StreamingProcool to SRT causese the following error.

![image](https://github.com/user-attachments/assets/082d20ea-f9b1-463d-b80d-4b5f9652daca)

The output path is always RTMP so that is probably the reason for this error.

**Update**
Changing rtmp to srt in the output url did not fix the issue.

**Comment by xpouyat** [comment]
Hello, SRT is only supported for Live encoding, not for live pass-through. Are you using Live Encoding ?

**Comment by sturlath** [comment]
ah.. that must be it.. no I´m just doing live pass-through. 

` Encoding = new LiveEventEncoding { EncodingType = LiveEventEncodingType.PassthroughBasic }`

maybe it would be good to fire of erro (or log it) if these settings don´t match?

**Comment by xpouyat** [comment]
Sure. I added some checks in dev branch https://github.com/microsoft/MK.IO/commit/ada5f595778bd5f02045bdfe991f414cca21ae9a

**Comment by xpouyat** [comment]
In latest release https://github.com/microsoft/MK.IO/releases/tag/v2.1.0
