### ISSUE TITLE
Regex and API mismatch (for at least container name length)

### ISSUE THREAD

**Issue by sturlath** [microsoft/MK.IO#36]
When calling the following

`var liveOutputAsset = await client.Assets.CreateOrUpdateAsync(outputAssetName, containerName, "dev", "live output asset");`

with a containerName with caps letters I get
> Value does not respect regex pattern ^(?=.{3,63}$)[a-z0-9]+(-[a-z0-9]+)*$. (Parameter 'containerName') 

also indicating that the lenght limit is between 3 and 63 but then if I fix my issue with `containerName.ToLower()` and pass it in I get this error from the API telling me its between 2 and 32.

```
Bad Request : Validation failed. Field name:'mladenblazortest-7961e6df-de353968' is invalid: ['Length must be between 2 and 32.']

Status: 400
Response: 
{
  "error": {
    "code": "1000.2000.1000.1080",
    "detail": "Validation failed. Field name:'mladenblazortest-7961e6df-de353968' is invalid: ['Length must be between 2 and 32.']"
  },
  "ref": "695adf4c-1149-4827-a810-fceb464c2436",
  "status": 400
}
```

**Comment by xpouyat** [comment]
Hello, thanks for the issue.
The container name in Azure has the following restriction https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata#container-names which seem different from the message from MK.IO.
I will check with MediaKind.

**Comment by xpouyat** [comment]
This is strange, I cannot repro. My code :

```
// create asset
string name = "mladenblazortest-7961e6df-de353968";

// list assets
var mkioAssetsResult = client.Assets.List(null, $"name eq '{name}'", null, null);

// it works
```

Is `dev` really the name of your storage ?

**Comment by xpouyat** [comment]
Thanks.
I don't hit the API error telling that container name should between 2 and 32. I used your code and added .ToLower(). 

```
var outputAssetName = MKIOClient.GenerateUniqueName("MladenBlazortest").ToLower();
var containerName = "asset-" + outputAssetName;
var liveOutputAsset = await client.Assets.CreateOrUpdateAsync(outputAssetName, containerName, "eventstreamingdev", "live output asset");
```

I also test with longer name, without any issue.

`var outputAssetName = MKIOClient.GenerateUniqueName("MladenBlazortest", 12).ToLower();`

**Comment by sturlath** [comment]
Ok sorry for this! I was mixing things up! Its the `client.LiveEvents.CreateAsync` code that has this error and not `client.Assets.CreateOrUpdateAsync` I just assumed it because that code is before the other one and I for some reason used a longer name after figuring out the `ToLower() `(at least I think I did that).

 ```csharp
    var LiveEventName = "MladenBlazortestMladenBlazortest"; // for super long name
    var liveEvent = await client.LiveEvents.CreateAsync(MKIOClient.GenerateUniqueName(LiveEventName), "uksouth", new LiveEventProperties
    {
        Description = "live event description",
        Input = new LiveEventInput
        {
            StreamingProtocol = LiveEventInputProtocol.RTMP
        },
        StreamOptions = ["Default"],
        Encoding = new LiveEventEncoding { EncodingType = LiveEventEncodingType.PassthroughBasic }
    }, tags, CancellationToken.None);
```

The error message doesn´t say anything about what is causing the issue.. if it would have said something like 

> "The Live event name needs to have lenght between 2-32"

I would probably have cought it.

**Comment by xpouyat** [comment]
This makes sense. I can repro now. I am adding some checks and tests for the live event name (and also tags).

**Comment by xpouyat** [comment]
In latest release https://github.com/microsoft/MK.IO/releases/tag/v2.1.0
