### ISSUE TITLE
StreamingLocatorContentKey.Type read-only

### ISSUE THREAD

**Issue by mc0re** [microsoft/MK.IO#40]
With one of the recent updates properties `StreamingLocatorContentKey.Type` and `StreamingLocatorContentKey.PolicyName` became read-only. How am I supposed to create a `StreamingLocatorProperties.ContentKeys` array now?

Background: I want to define the key value. This code used to work.

```csharp
        var locatorProps = new StreamingLocatorProperties
        {
            AssetName = assetName,
            ContentKeys = [
                new StreamingLocatorContentKey
                {
                    Type = StreamingLocatorContentKeyType.CommonEncryptionCenc,
                    Id = keyId.ToString(),
                    Value = Convert.ToBase64String(keyValue),
                    PolicyName = DrmConstants.ContentPolicy,
                    LabelReferenceInStreamingPolicy = DrmConstants.ReferenceStreamingPolicy
                }],
            DefaultContentKeyPolicyName = DrmConstants.ContentPolicy,
            StreamingPolicyName = DrmConstants.StreamingPolicy,
            StartTime = DateTime.Now
        };
```

**Comment by xpouyat** [comment]
Hello,
Thanks for the message.
I will investigate. The OpenAPI specs flags these properties as readOnly...

[https://api.io.mediakind.com/doc/openapi.json](https://api.io.mediakind.com/doc/openapi.json)

![2024-09-19_13h41_55](https://github.com/user-attachments/assets/6483bc34-f9b9-4927-a038-ddaaa45040e4)

**Comment by xpouyat** [comment]
I tested and I confirm these properties should not be read-only. I informed MediaKind and I am pushing an update of the SDK today. https://github.com/microsoft/MK.IO/pull/41/commits/4a6041dbf1cbf11f086c76082482d5827ba54f0a
Thanks for your feedback !
