### ISSUE TITLE
Parameter validation for asset creation is too strict

### ISSUE THREAD

**Issue by Saancreed** [microsoft/MK.IO#6]
Hi, and thanks for creating this library, it's been really helpful in migrating some of our projects from Azure Media Services to MK.IO.

While most of the migrations was fairly smooth, there are some minor thing I've noticed that are not consistent with both old AMS API and MK.IO API:

1. The first one is the requirement to pass a non-null container name when creating new assets. Being able to provide it is certainly useful when migrating existing assets that have already been transcoded (so we can select existing Azure Storage containers) but less so when content managers want to upload new assets to the service. From my observations, [MK.IO API will happily accept creation requests with `properties.container` not set in the request body](https://docs.mk.io/reference/put_apiamsproject_nameassetsasset_name) and autogenerate one that looks like `asset-{assetId}`, which is similar to what AMS did but currently not achieveable with this library because we don't know the `assetId` before its creation. While having this is not by any means a requirement for us, we would appreciate being able to keep container names in sync with related assets and without having to use `alternateId`s for this.

2. The library rejects attempts to create assets (and possibly other resources) with spaces in their names. Because the name usually ends up as the last segment in API request path, I can easily work around this by doing dumb `name.Replace(" ", "%20")` URL encoding before calling relevant methods but I think it would be much simpler if the library did this internally on its own.

**Comment by xpouyat** [comment]
Many thanks for your input.
I will test your comments 1 and 2 and will update the SDK accordingly.

**Comment by xpouyat** [comment]
Hi @Saancreed, [version ](https://github.com/microsoft/MK.IO/releases/tag/v1.6.2) should bring what you asked for.

**Comment by Saancreed** [comment]
Thank you, we will upgrade to that version sometime next week. I'll let you know if we find any problems but the code changes look good (assuming that there's no need to manually perform any URL encoding) so for now I suppose this issue can be closed.
