### ISSUE TITLE
docs line missing

### ISSUE THREAD

**Issue by sjorsmiltenburg** [microsoft/MK.IO#7]
Hi, Thank you for creating this library.

a minor thing: 
It seems that the documentation in the readme is incomplete / duplicated
on the 3rd line of the following quote

> // create asset
> var newAssetName = MKIOClient.GenerateUniqueName("asset");
> var newasset = client.Assets.CreateOrUpdate(newAssetName, newAssetName, "storagename", "description of my asset");
> 
> // create asset and use labels to tag it
> newAssetName = MKIOClient.GenerateUniqueName("asset");
> newasset = client.Assets.CreateOrUpdate(
>     newAssetName,
>     newAssetName,
>     "storagename",
>     "description of asset using labels",
>     AssetContainerDeletionPolicyType.Retain,
>     null,
>     new Dictionary<string, string>() { { "typeAsset", "source" } }
>     );

**Comment by xpouyat** [comment]
Thanks! The sample shows how to create two assets but I will clarify.

**Comment by sjorsmiltenburg** [comment]
Only now I see that I needed to scroll to the right to see the right part of the sentence (facepalm)
there was no error all along... sorry about the confusion.

I do have another remark on the docs though. It is info that I also find missing in the official mk.io docs.

I would like to see a complete code example on how to add a new video to MK.IO.

I am currently trying to figure this out myself based on logical reasoning and the text from other issues
I mean (not sure this is the flow):
- (azure) create an input container in azure
- (azure) create an inputblob in the input container
- (azure) upload a file into the input container
- (azure) create an output container in azure
- (mk.io) create an input asset matching the input container
- (mk.io) create an output asset matching the output container
- (mk.io) create a job that does the transform (assuming the transform is already created)

- .. this is where I am still figuring things out currently

- (mk.io) poll the job for completion
- (mk.io) set up the streaming endpoint for the asset
- (mk.io) set up the streaming locator for the asset
- output: a streaming url

**Comment by xpouyat** [comment]
This is the flow I think

- (mk.io) create an input asset (it will create the container for you)
- (azure) upload a file into the input container as blob
- (mk.io) create an output asset (it will create the container for you)
- (mk.io) create a job that does the transform (assuming the transform is already created)
- (mk.io) poll the job for completion
- (mk.io) set up the streaming locator for the asset
- output: a streaming url

Note : streaming endpoint has to created one time, you can use it will all your assets.

**Comment by sjorsmiltenburg** [comment]
thanks for the info, this will simplify my code somewhat.
As 'an mk.io beginner' I would love to see this flow in the docs / code sample

**Comment by xpouyat** [comment]
You are right. I will see how to add that.

**Comment by sjorsmiltenburg** [comment]
In case someone is interested, I got it working with the following code

MKIOVideo - my database entity for keeping track of the video

`public sealed class MKIOVideo
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    public Guid VideoId { get; set; }
    public string BackendString { get; set; } = "";

    public string AzureInputBlobContainerName
    {
        get
        {
            return $"{VideoId}-{BackendString}-input";
        }
    }

    public string AzureOutputBlobContainerName
    {
        get
        {
            return $"{VideoId}-{BackendString}-output";
        }
    }

    public string AzureInputBlobName
    {
        get
        {
            return $"{VideoId}-{BackendString}-inputblob";
        }
    }

    public string MkIoInputAssetName
    {
        get
        {
            return $"{VideoId}-{BackendString}-input-mkio";
        }
    }

    public string MkIoOutputAssetName
    {
        get
        {
            return $"{VideoId}-{BackendString}-output-mkio";
        }
    }

    public string JobName
    {
        get
        {
            return $"job-{VideoId}";
        }
    }

    public string JobStatus { get; set; } = "Unknown";
    public string OriginalFilePath { get; set; } = "";// the original path of the uploaded video file
    public string StreamingUrl { get; set; } = "";

    [Obsolete]
    public MKIOVideo()
    {
        //for EF
    }

    public MKIOVideo(string uploadFilePath, string backendString)
    {
        VideoId = Guid.NewGuid();
        BackendString = backendString;
        OriginalFilePath = uploadFilePath;
    }`

Server Side

`private async Task StartProcessingVideo(MKIOVideo mkioVideo)
{
    IMKIOClient client = GetMKIOClient();
    //this call will create the container in azure (if it does not yet exist)
    var MKIOInputAsset = await client.Assets.CreateOrUpdateAsync(
        assetName: mkioVideo.MkIoInputAssetName,
        containerName: mkioVideo.AzureInputBlobContainerName,
        storageName: _mkioStorageAccountName,
        description: "input asset",
        containerDeletionPolicy: AssetContainerDeletionPolicyType.Delete); //we aim to delete this afterwards

    await UploadFileToAzure(mkioVideo);

    //this call will create the container in azure (if it does not yet exist)
    var MKIOOutputAsset = await client.Assets.CreateOrUpdateAsync(
        assetName: mkioVideo.MkIoOutputAssetName,
        containerName: mkioVideo.AzureOutputBlobContainerName,
        storageName: _mkioStorageAccountName,
        description: "output asset",
        containerDeletionPolicy: AssetContainerDeletionPolicyType.Retain);

    var jobSchema = await client.Jobs.CreateAsync(
        transformName: _transformName, //manually created in the mk.io portal
        jobName: mkioVideo.JobName,
        new JobProperties()
        {
            Input = new JobInputAsset(
                assetName: mkioVideo.MkIoInputAssetName,
                files: new List<string>() { mkioVideo.AzureInputBlobName }
                ),
            Outputs = new List<JobOutputAsset>
            {
                    new JobOutputAsset { AssetName = mkioVideo.MkIoOutputAssetName }
            }
        });
}

 private async Task UploadFileToAzure(MKIOVideo mkioVideo)
 {
     BlobServiceClient blobServiceClient = new BlobServiceClient(_azureStorageConnectionString);            
     var blobContainerClient = blobServiceClient.GetBlobContainerClient(mkioVideo.AzureInputBlobContainerName);
     var httpRequest = HttpContext.Request;
     var postedFile = httpRequest.Form.Files[0];

     var fileId = Guid.NewGuid();
     byte[] buffer = new byte[postedFile.Length];

     using (var memoryStream = new MemoryStream())
     {
         await postedFile.CopyToAsync(memoryStream);
         buffer = memoryStream.ToArray();
         memoryStream.Position = 0;
         var blobContentInfo = await blobContainerClient.UploadBlobAsync(mkioVideo.AzureInputBlobName, memoryStream);
     }
 }

private async Task<MKIOVideo> UpdateJobStatus(MKIOVideo mkioVideo)
{
    var mkioClient = GetMKIOClient();
    var job = await mkioClient.Jobs.GetAsync(_transformName, mkioVideo.JobName);
    mkioVideo.JobStatus = job.Properties.State.ToString();

    if (job.Properties.State == JobState.Finished)
    {
        var streamingLocators = await mkioClient.Assets.ListStreamingLocatorsAsync(mkioVideo.MkIoOutputAssetName);
        var streamingLocatorName = $"{mkioVideo.Id}-streaminglocator";
        if (streamingLocators != null && !streamingLocators.Any())
        {
            var mklocator = await mkioClient.StreamingLocators.CreateAsync(streamingLocatorName,
                new StreamingLocatorProperties
                {
                    AssetName = mkioVideo.MkIoOutputAssetName,
                    StreamingPolicyName = PredefinedStreamingPolicy.ClearStreamingOnly
                });
        }
        var streamingUrls = await mkioClient.StreamingLocators.ListUrlPathsAsync(streamingLocatorName);

        //Store streaming urls in db

        //clean up the job
        await mkioClient.Jobs.DeleteAsync(_transformName, mkioVideo.JobName);

        //clean up the input asset, because we have set Mkioasset.AssetContainerDeletionPolicyType.Delete it will also delete the azure side (container + blobs)
        await mkioClient.Assets.DeleteAsync(mkioVideo.MkIoInputAssetName);
    }

    await _dbContext.SaveChangesAsync();
    return mkioVideo;
}

`

**Comment by sjorsmiltenburg** [comment]
As you might read from the code:
creating an input asset through mkio will indeed create the azure container for you, 
but the azure container does not seem to be ready for file upload directly after this method returns.
Therefore in my code I create it in azure prior to calling the mkio call to ensure it's ready for upload.

I don't know if this is a bug, but it is inconvenient.
Do you think I should report this to mk.io? (because i doubt it is in your library)?

**Comment by xpouyat** [comment]
The sample code is now in the main branch and I added a reference to it in the readme.
Thanks for your suggestion !
