### ISSUE TITLE
job.Status seems wrong

### ISSUE THREAD

**Issue by sjorsmiltenburg** [microsoft/MK.IO#9]
Hi,

I am polling the job status and I get back job.Status = "WaitingForActivation".
On the mk.io portal I see the job has 'job state' = "Finished"
While 'state' might not be the same as 'status', there are no other properties that indicate it is 'finished'

I'm using the latest version 1.6.1

My code: 
var mkioClient = GetMKIOClient();
var job = mkioClient.Jobs.GetAsync(_transformName, mkioVideo.JobName);

The weird thing is that JobState seems to be an enum in your code and the returned value is not in the list:
https://github.com/microsoft/MK.IO/blob/main/MK.IO/Job/Models/JobState.cs

Seems like a bug, or am I missing something?

**Comment by sjorsmiltenburg** [comment]
ok, I feel completely stupid.. There is no bug.
I forgot to await the call and was looking at the wrong object type
I appologize for my stupidity. Please close this issue.

**Comment by xpouyat** [comment]
No problem ! Thanks for the update.
